### ISSUE TITLE
v.30 on Openshift cluster references nonexistent image of ose-kube-rbac-proxy

### ISSUE THREAD

**Issue by hanipman** [devfile/devworkspace-operator#1311]
### Description
devworkspace operator v.30 installation on Openshift 4 cluster tries to pull registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:fde6314359436241171f6361f9a1e23c60bdf2d421c0c5740734d1dcf5f01ac2

### How To Reproduce
1. For new install, find operator v.30 in OperatorHub
2. Installed with default configs
3. pods for devworkspace-controller-manager and devworkspace-webhook-server fail with ImagePullBackOff error

### Expected behavior
devworkspace-controller-manager and devworkspace-webhook-server pods should deploy properly
operator should install with existing ose-kube-rbac-proxy image in redhat registry
 
### Additional context
Originally was on v.29. Subscription is set to automatic approval

**Comment by jsanchezmartinez** [comment]
Hi,
I can confirm this is also happening to us when updating from 0.29.0 to 0.30.0:

> `Failed to pull image "registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:fde6314359436241171f6361f9a1e23c60bdf2d421c0c5740734d1dcf5f01ac2": reading manifest sha256:fde6314359436241171f6361f9a1e23c60bdf2d421c0c5740734d1dcf5f01ac2 in registry.redhat.io/openshift4/ose-kube-rbac-proxy: manifest unknown`.

**Comment by Ruckus0143** [comment]
This helps https://access.redhat.com/solutions/7084768. 
Edit devworkspace-operator.v0.30.0 CSV to replace the image from registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:fde6314359436241171f6361f9a1e23c60bdf2d421c0c5740734d1dcf5f01ac2 to registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:514e9e03f1d96046ff819798e54aa5672621c15805d61fb6137283f83f57a1e3
Edit devworkspace-webhook-server deployment to sub out the same image.

**Comment by AObuchow** [comment]
Sorry for the delayed reply, we've been working on addressing this issue downstream, see https://issues.redhat.com/browse/CRW-7172.
This issue only affects the downstream productized version of DevWorkspace Operator (i.e. when installed through OLM or OperatorHub on OpenShift) and not the upstream version.

The workaround [mentioned](https://github.com/devfile/devworkspace-operator/issues/1311#issuecomment-2321240807) by @Ruckus0143 is our currently provided workaround until this issue is resolved, see https://access.redhat.com/solutions/7084768.

**Comment by AObuchow** [comment]
The fix for this issue on x86 and IBM Z (s390x) platforms has been shipped: https://access.redhat.com/errata/RHBA-2024:6449

Please note:
- If DevWorkspace Operator 0.30.0 was previously installed, you will need to apply the workaround from https://access.redhat.com/solutions/7084768 OR delete the clusterserviceversion for DevWorkspace Operator 0.30.0 with `oc delete clusterserviceversion devworkspace-operator.v0.30.0 -n <operator-install-namespace>`. The `<operator-install-namespace>` refers to the namespace where DevWorkspace Operator is installed, which is openshift-operators by default, e.g. `oc delete clusterserviceversion devworkspace-operator.v0.30.0 -n openshift-operators`.
- This fix only works for x86 and IBM Z (s390x) platforms. The fix for PPC is currently being worked on and will be coming soon.

I will mark this issue as resolved when the fix for PPC becomes available.

**Comment by AObuchow** [comment]
The fix for this issue that works for all platforms (x86, s390x and PPC) has been shipped: https://access.redhat.com/errata/RHBA-2024:6628

An update for DevWorkspace Operator 0.30.2 should appear in the Installed Operators page on OpenShift.

Please note: 

If upgrading from DevWorkspaceOperator v0.30.0 or v0.30.1, you may have to delete the existing devworkspace-operator.v0.30.0 or devworkspace-operator.v0.30.1 ClusterServiceVersion after initiating the upgrade (depending on which version of DevWorkspace Operator is installed). This is only required if your install of DevWorkspace Operator v0.30.0 (on all platforms) or v0.30.1 (on PPC) is broken.

The above can be done from the OpenShift Console UI or with `oc delete clusterserviceversion devworkspace-operator.v0.30.0 -n <operator-install-namespace>` or `oc delete clusterserviceversion devworkspace-operator.v0.30.1 -n <operator-install-namespace>`. The <operator-install-namespace> refers to the namespace where DevWorkspace Operator is installed, which is openshift-operators by default.
