### ISSUE TITLE
Should we consider reconciliation of commands and projects?

### ISSUE THREAD

**Issue by l0rd** [devfile/devworkspace-operator#273]
The fields `commands` and `projects` of a `DevWorkspace` are not managed by the `DevWorkspace` operator.

That means that tools that use those fields need to:
- directly watch for changes to the CR
- eventually create/delete kubernetes objects as a consequence of changes to the CR

For example, in a Che-Theia workspace scenario, if a new project is added to a `DevWorkspace`, Che-Theia needs to immediately git clone and add a new workspace. If the editor is not `Che-Theia` but `IntelliJ`, we need to implement it on that editor too.

That has a couple of problems:
- tool needs to (re-)implement reconciliation
- possible inconsistency in how reconciliation is implemented

Possible reconciliations handled by the DevWorkspace controller:
- [ ] `projects` --> #205
- [ ] `commands` --> CM mounted as files?

**Comment by amisevsk** [comment]
To add on to the topic of reconciling commands, what is our plan for `postStart` and `preStop` commands? I had a brief idea of implementing them in the DevWorkspace Operator via exec, since we track the workspace lifecycle closely, but I'm not sure if it should be a concern for the operator or not. `preStop` may be rather hard to implement in a workspace component, as components generally don't get much notice that they being deleted.

**Comment by amisevsk** [comment]
Closing as out of date:
* Projects are reconciled via the project-clone container
* Commands are stored in the mounted metadata configmap and can be read within a workspace
* postStart/preStop events are handled via lifecycle hooks.
