### ISSUE TITLE
project clone operation is altering files after the clone operation

### ISSUE THREAD

**Issue by benoitf** [devfile/devworkspace-operator#447]
When cloning the branch devfile2 of https://github.com/che-samples/spring-petclinic with devworkspace 
https://gist.githubusercontent.com/benoitf/08bffac9b6e5dbbddacf7f462750c07e/raw/61dffd9df0980f4a8535ff5a44c77eab18f32a8b/devworkspace.yaml

git status output is
```bash
bash-5.0 /projects/spring-petclinic $ git status
On branch devfilev2
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    .vscode/extensions.json

no changes added to commit (use "git add" and/or "git commit -a")
```

while if I do a fresh clone with the cli, the output is:

```
$ git status
On branch devfilev2
Your branch is up to date with 'origin/devfilev2'.

nothing to commit, working tree clean
```

So it seems project-clone operation is ignoring all files listed by .gitignore while git cli is not doing anything like that

**Comment by amisevsk** [comment]
Looking into this, it appears to happen due to OOMKilled in the project clone container -- the container is killed partway through checkout/setting up the repo, which leaves the repo in an inconsistent state. Subsequent runs see that the project is cloned to disk, and so skip syncing branches, etc.

I've bumped the memory limit to 1Gi in https://github.com/devfile/devworkspace-operator/pull/453, which is enough memory to clone `openshift/console` (a go project that contains a vendor directory) without reproducing this issue.

**Comment by amisevsk** [comment]
Created https://github.com/devfile/devworkspace-operator/issues/454 for follow-up
