### ISSUE TITLE
DevWorkspace operator should not ignore SA dockercon if additional pullSecret is configured

### ISSUE THREAD

**Issue by sleshchenko** [devfile/devworkspace-operator#459]
Issue is well described in https://issues.redhat.com/browse/CRW-1925
The main idea - after users configures pull secret, they are not able to use internal registry without adding explicitly SA token into that pull secret.

I suppose it's not handled in DWO as well, so DWO should mount additional pull secret in addition to workspace SA dockerconf but not instead.

**Comment by sparkoo** [comment]
Issue is that when we don't define `imagePullSecret` for the workspace deployment, OpenShift adds default one for the service account. That's why OpenShift registry works at first. Once we define custom user `imagePullSecret`, OpenShift does not add it's default one, thus we cannot authenticate against openshift registry anymore.

 

The code responsible for provisioning image pull secrets lives here https://github.com/eclipse-che/che-server/blob/main/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/ImagePullSecretProvisioner.java#L66 and combined into deployment here https://github.com/eclipse-che/che-server/blob/main/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/environment/PodMerger.java#L74. It is possible to define multiple pull secrets for the deployment, so I think we should be able to always include the che-workspace SA dockerfcg secret in the deployment.

**Comment by sleshchenko** [comment]
fixed by https://github.com/devfile/devworkspace-operator/pull/566
