### ISSUE TITLE
Image field in manifests should be updated with $DWO_IMG before building bundle

### ISSUE THREAD

**Issue by JPinkney** [devfile/devworkspace-operator#531]
Currently if you do:
```
make docker build_bundle_image build_index_image register_catalogsource
```
the manifests will stay the same and you will produce a bundle that uses `quay.io/devfile/devworkspace-controller:next` as the controller image. Instead, we should make it so that `build_bundle_image` replaces that image with whatever is stored in $DWO_IMG before proceeding with the build

**Comment by amisevsk** [comment]
The tedious thing here is that we want `build_bundle_image` and `build_index_image` to generally use defaults since they write to tracked files in the repo. If we use `$DWO_IMG`, then testing out the OLM deploy will change files in the repo, and those changes would need to be dropped before committing.

It's possible to work around this issue by setting `DEFAULT_IMAGE=$DWO_IMG` before building.

**Comment by amisevsk** [comment]
Thinking about this a bit more, it may be the case that the cure is worse than the disease. `$DWO_IMG` as it's currently used works because we generate files in two separate streams:

- `make generate_deployment` uses env vars and outputs templates to `deploy/current`, which is gitignored.
- `make generate_default_deployment` *ignores* env vars and outputs templates to the tracked directory `deploy/deployment`

For OLM bundles, we only use one directory (`deploy/bundle`) which is updated when `generate-deployment.sh --generate-olm` is run (note `--generate-olm` implicitly assumes `--use-defaults` here, so env vars are ignored).

The way to fix this issue would be to do similar to what we have with the non-OLM deployment -- i.e. have separate streams for the OLM commands like `build_bundle_image` and `build_default_bundle_image`. This could make the Makefile significantly more complicated.
