### ISSUE TITLE
Multiarch support in upstream

### ISSUE THREAD

**Issue by sleshchenko** [devfile/devworkspace-operator#559]
Since CRW depends on DevWorkspace Operator it's needed to make sure it supports multiarch.

I assume it does not, since controller dockerfile does not have GO_ARCH, and project clone's one hardcodes amd64.

**Comment by nickboldt** [comment]
Well, the images in RHEC for the 0.8.0 release are multi-arch X, Z, and P.

https://catalog.redhat.com/software/containers/devworkspace/devworkspace-project-clone-rhel8/60ec9f47744684587e2186a1?architecture=ppc64le&container-tabs=overview&gti-tabs=registry-tokens
https://catalog.redhat.com/software/containers/devworkspace/devworkspace-rhel8-operator/60ec9f48744684587e2186a2?architecture=s390x&container-tabs=overview&gti-tabs=registry-tokens
https://catalog.redhat.com/software/containers/devworkspace/devworkspace-operator-bundle/60ec9f48744684587e2186a3?architecture=s390x&container-tabs=overview&gti-tabs=registry-tokens

But we may have to build an upstream equivalent in GH actions / travis to achieve this in Che, unless Che also depends on the RHEC released product images.

**Comment by AObuchow** [comment]
@nickboldt Are we aiming to support only the following platforms `amd64, arm64, ppc64le, s390x` (i.e. are those the only officially supported platforms for Che & DevSpaces) ?

It'd be nice to also support `darwin/arm64` for apple silicon, but this might be a bit tricky: The [`ubi8/go-toolset`](https://catalog.redhat.com/software/containers/ubi8/go-toolset/5ce8713aac3db925c03774d1?architecture=arm64&image=6530330f81d889df93734661) that we're [using](https://github.com/devfile/devworkspace-operator/blob/main/build/Dockerfile#L17) to build DWO does not have an image available for `darwin/arm64`, unfortunately.

**Comment by nickboldt** [comment]
upstream: amd64 only, though some Mac users have also requested `arm64` so they can run on their local M1 macs (@l0rd for example). A handful of Che containers are built for ppc64le and arm64, but as we don't have a complete set yet, only ONE arch can actually be deployed.

downstream: amd64, s390x, ppc64le - check the release notes https://access.redhat.com/documentation/en-us/red_hat_openshift_dev_spaces/3.8/html-single/release_notes_and_known_issues/index#supported-platforms

**Comment by l0rd** [comment]
For the record I don't have a M1 Mac 😀

**Comment by AObuchow** [comment]
Just wanted to clarify some requirements for this:

1. We need the devworkspace-controller and project-clone images built for all platforms (this is the bare minimum)
2. We need the DWO index, bundle and digest images built for all platforms.
3. We don't need multi-arch builds to work with both Docker _and_ podman. From my understanding, podman can't do multi-arch builds, and buildah is required instead. IMO, since multi-arch builds will generally be done by our GH workflows (which use [docker](https://github.com/devfile/devworkspace-operator/blob/main/.github/workflows/next-build.yml#L48-L56)), it's fine to only have multi-arch builds working when using Docker. 

Point 2. is slightly complicated by the fact that `opm serve` binds to a port. When doing a multi-arch build with Docker buildx, each platform image is built in parallel, which leads to port-already-in-use conflicts since we're using the default port. An easy but inefficient workaround is to disable parallelism for these builds (it's not the biggest deal if builds take a bit longer on [main](https://github.com/devfile/devworkspace-operator/blob/main/.github/workflows/next-build.yml#L20)). A better solution may be to specify a port (with [`opm serve -p ...`](https://github.com/operator-framework/operator-registry/blob/master/docs/design/opm-tooling.md#serve)) and try another port if it is already in use. 

If any of my assumed requirements are incorrect, please correct me.

**Comment by deerskindoll** [comment]
RN status: upstream only
