### ISSUE TITLE
Automounting git credentials creates secret for each workspace

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#580]
### Description

In order to support automounting git credentials (see https://github.com/devfile/devworkspace-operator/pull/564), we need to merge credentials into one secret to mount all credentials at once. However, since the created secret is named after the current workspace ID, this means that we're creating multiple identical secrets in the user's namespace. We could instead potentially use a fixed secret name instead and share it across all workspaces in a given namespace.

On one hand, generated names could result in issues where a namespace has a secret quota (especially if a user has a large number of stopped workspaces). On the other hand, this would be an out-of-lifecycle resource that we create and wouldn't be deleted automatically, which would require documentation at minimum.

(I hope this isn't a discussion that's already happened while I was off)

**Comment by JPinkney** [comment]
I don't think we had the discussion but I'm more then happy to revisit the topic. Che technically doesn't have this issue because they don't currently combine multiple secrets into one AFAIK, so the number of secrets in namespace would only be the number of different personal access tokens they have for different websites.

If we go with a common name could we technically tie the secret to the devworkspace controller? That way if the controller is cleaned up then the secret will disappear as well. Then on every reconcile of the devworkspace operator we can check if we need to reconcile the git-credentials secret to add/remove personal access tokens and just keep the one secret upto date. The rest of the functionality can otherwise stay the same
