### ISSUE TITLE
Drop v1alpha1 in DevWorkspace v0.11.0

### ISSUE THREAD

**Issue by sleshchenko** [devfile/devworkspace-operator#599]
v1alpha1 was deprecated in DWO 0.8.0 in favor of v1alpha2,
At the time OpenShift 4.9 is coming it makes sense to fully drop v1alpha2 from DWO 0.10.0 release.

**Comment by JPinkney** [comment]
Looking into this more, it looks like this is a multi-step process.
According to the [openshift docs](https://docs.openshift.com/container-platform/4.8/operators/operator_sdk/osdk-generating-csvs.html#olm-dependency-resolution-removing-crd-version_osdk-generating-csvs) we need to do a few things:
1. Set `served: false` in the DevWorkspace CRD
2. Update the devfile/api dependency so that we pull in the DevWorkspace CRD with `served: false`
3. Release DWO 0.10 with the updated v1alpha1 DevWorkspace CRD
4. Drop v1alpha1 DevWorkspace completely from the devfile/api
5. Drop v1alpha1 DevWorkspace completely from DWO
6. Remove the v1alpha1 CRD from the OLM Manifests

**Comment by amisevsk** [comment]
This task is on hold until OpenShift console adopts v1alpha2 as a default. If we stop serving v1alpha1 at this point, the Web Terminal Operator will not function correctly.

**Comment by amisevsk** [comment]
Closing this issue for now as the `v1alpha1` APIVersion is still used in the OpenShift Console and so cannot be removed until current versions of the console go to EOL.
