### ISSUE TITLE
Add option to specify clone options

### ISSUE THREAD

**Issue by benoitf** [devfile/devworkspace-operator#757]
### Description
Today, starting a workspace with for example https://github.com/che-incubator/che-code is taking a long time 

But if I'm interested only in the current main branch, then I could have a way to specify the depth (history of commits) I want

For example, in github actions https://github.com/actions/checkout I have

```
    # Number of commits to fetch. 0 indicates all history for all branches and tags.
    # Default: 1
    fetch-depth: ''
```

so I would like to be able to specify the depth

**Comment by benoitf** [comment]
One option could be to fetch only one commit of history at clone time and fetch all the history once the workspace has been started (lazy mode to fetch full history)

**Comment by amisevsk** [comment]
This seems like something that would be useful to have somewhere in the `devfile/api` spec itself rather than as a DWO-only feature.

**Comment by nickboldt** [comment]
I could also see value in being able to specify a `sparseCheckoutDir` or `workingDir` or `regexPathExcludes` or `regexPathIncludes` so that the resulting cloned project can exclude paths not needed in the clone.

For example, https://github.com/crw-samples/jboss-eap-quickstarts/blob/devfilev2/devfile.yaml will clone the whole project but only one folder, https://github.com/crw-samples/jboss-eap-quickstarts/tree/devfilev2/kitchensink-jsp is referred by the devfile.

Similarly https://github.com/crw-samples/quarkus-quickstarts/tree/devfilev2 has a devfile which uses only the https://github.com/crw-samples/quarkus-quickstarts/tree/devfilev2/getting-started folder, which is 2M instead of 20M.

**Comment by amisevsk** [comment]
To update this issue for (now) 2024: DWO has the following features built in:

* Sparse checkouts are supported by the operator via the `sparseCheckout` attribute on projects [[doc](https://github.com/devfile/devworkspace-operator/blob/main/docs/additional-configuration.adoc#configuring-sparse-checkout-for-projects)]
* In addition, for starter projects we support the `subDir` field, which first clones a whole project and then saves only a subdirectory of that project (which would be useful for the sample mentioned by Nick above

Both of the above features were added in https://github.com/devfile/devworkspace-operator/pull/1130 and are a part of DWO v0.22 and onward.

I'm closing this issue as I don't believe we have any intention of implementing shallow clones in DWO; in general, while shallow cloning is useful in CI builds, it's not recommended for most development flows and would likely cause more issues than it resolves.

If we want to consider enabling partial clones (e.g. a blobless clone), we should open a separate issue.
