### ISSUE TITLE
DWO should support per-namespace per-workspace PVC size configuration

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#836]
### Description
Currently, it's possible to configure the size of the common PVC by creating a configmap in the workspace's namespace. However, this configmap only supports setting a value for the size of the common PVC, and this size is used for per-workspace PVCs as well. Instead, this configmap should support setting per-workspace PVC size as well.

**Comment by AObuchow** [comment]
This feature potentially depends on https://github.com/devfile/devworkspace-operator/pull/827 since we are making the PVC size parameter a `resource.Quantity` [rather than a string](https://github.com/devfile/devworkspace-operator/pull/827/files#diff-619dac889e7b2b7d474d8460de5eee5ae385474e35058899fd4dfec868bcbfe1R38). However, since the API for the configmap is already using a string, we could just parse the quantity.

**Comment by amisevsk** [comment]
It probably makes sense to keep the namespaced config strings, as it currently is, since there is no validation on that field. These strings can be parsed as use-time to more accurately report and handle errors.
